<?php

return [
    'lead_email' => 'trisparksoftwaresolutions@gmail.com',
    'data_page_password' => 'nisha@123',

    'services' => [
        'web-development' => [
            'slug' => 'web-development',
            'icon' => '</>',
            'icon_class' => 'icon-blue',
            'title' => 'Web Design / Development',
            'summary' => 'Custom web applications built with Laravel, React, Next.js, and modern frameworks.',
            'description' => 'We build high-performance websites and web applications focused on speed, security, and scalable architecture. From landing pages to complex internal systems, every build is optimized for long-term maintainability and growth.',
            'features' => [
                'Progressive Web Apps',
                'Admin Panel',
                'Custom, responsive, and modern websites',
                'API Integration',
            ],
            'deliverables' => [
                'Technical planning and architecture blueprint',
                'Responsive frontend and robust backend implementation',
                'Performance optimization and SEO-ready foundation',
                'Deployment, monitoring, and post-launch support',
            ],
            'timeline' => '4-12 weeks',
            'recommended_technologies' => ['Laravel', 'React', 'Next.js', 'MySQL', 'AWS', 'TypeScript'],
        ],
        'mobile-app-development' => [
            'slug' => 'mobile-app-development',
            'icon' => '📱',
            'icon_class' => 'icon-pink',
            'title' => 'Mobile App Development',
            'summary' => 'Native iOS/Android and cross-platform mobile apps for exceptional experiences.',
            'description' => 'Our team delivers production-ready mobile applications with smooth UX, reliable performance, and scalable backend connectivity. We support full lifecycle delivery from discovery to app-store release and maintenance.',
            'features' => [
                'iOS & Android',
                'Cross-platform',
                'Push Notifications',
                'App Store Deployment',
            ],
            'deliverables' => [
                'Feature mapping and user flow planning',
                'Cross-platform or native app development',
                'QA across devices and OS versions',
                'Release support for Play Store and App Store',
            ],
            'timeline' => '6-16 weeks',
            'recommended_technologies' => ['Flutter', 'React Native', 'Firebase', 'AWS', 'TypeScript'],
        ],
        'agentic-ai-solutions' => [
            'slug' => 'agentic-ai-solutions',
            'icon' => 'AI',
            'icon_class' => 'icon-green',
            'title' => 'Agentic AI Solutions',
            'summary' => 'Custom AI agents, recommendation systems, visual AI, and intelligent workflow automation.',
            'description' => 'We design responsible AI systems that can analyze information, recommend actions, automate multi-step workflows, and integrate with existing business platforms. Solutions include custom LLM workflows, visual AI, domain-aware recommendation engines, and secure human-in-the-loop automation.',
            'features' => [
                'Agentic workflow automation',
                'Custom LLM and recommendation systems',
                'Visual AI and image analysis',
                'Responsible AI controls and audit trails',
            ],
            'deliverables' => [
                'AI opportunity and data-readiness assessment',
                'Model, retrieval, and agent workflow architecture',
                'Secure API and product integration',
                'Evaluation, monitoring, and human-review controls',
            ],
            'timeline' => '6-18 weeks',
            'recommended_technologies' => ['Python', 'AWS', 'Laravel', 'PostgreSQL', 'Docker', 'Redis'],
        ],
        'healthcare-rcm-analytics' => [
            'slug' => 'healthcare-rcm-analytics',
            'icon' => 'RCM',
            'icon_class' => 'icon-blue',
            'title' => 'Medical CRM & RCM Analytics',
            'summary' => 'Medical CRM platforms with EMR workflows, patient operations, and dashboards for major revenue-cycle KPIs.',
            'description' => 'We build medical CRM and healthcare revenue cycle platforms that bring patient and provider records, EMR workflows, workload tracking, authorization, eligibility, credentialing, communication, and analytics into one operational command center.',
            'features' => [
                'Patient, provider, and payer relationship management',
                'EMR-linked workflow and document management',
                'Clean claim and denial-rate analytics',
                'A/R aging and collection performance',
                'Authorization, eligibility, and credentialing status',
                'Workload, turnaround time, and team performance',
            ],
            'deliverables' => [
                'Medical CRM and RCM workflow mapping',
                'Role-based patient and operations command center',
                'RCM KPI and team performance dashboards',
                'Secure reporting, monitoring, and handover',
            ],
            'timeline' => '10-20 weeks',
            'recommended_technologies' => ['Laravel', 'React', 'Python', 'PostgreSQL', 'AWS', 'Docker'],
        ],
        'ui-ux-design' => [
            'slug' => 'ui-ux-design',
            'icon' => '🎨',
            'icon_class' => 'icon-orange',
            'title' => 'UI/UX Design',
            'summary' => 'Beautiful, intuitive interfaces designed with user research and prototyping.',
            'description' => 'We design interfaces that balance visual quality with usability. Our process focuses on user behavior, clear navigation, and design systems that help teams ship new features faster with consistency.',
            'features' => [
                'User Research',
                'Prototyping',
                'Design Systems',
                'Figma',
            ],
            'deliverables' => [
                'User journey and wireframe documentation',
                'High-fidelity UI mockups',
                'Interactive prototype for stakeholder validation',
                'Design system with reusable components',
            ],
            'timeline' => '3-8 weeks',
            'recommended_technologies' => ['Figma', 'React', 'Next.js', 'Framer Motion'],
        ],
        'automation-solutions' => [
            'slug' => 'automation-solutions',
            'icon' => '⚙️',
            'icon_class' => 'icon-green',
            'title' => 'Automation Solutions',
            'summary' => 'Intelligent workflow automation and DevOps solutions for your business.',
            'description' => 'We automate repetitive business and engineering workflows to reduce manual effort and improve reliability. This includes delivery pipelines, task orchestration, and operational dashboards for better visibility.',
            'features' => [
                'CI/CD Pipelines',
                'Workflow Automation',
                'Cloud Deployment',
            ],
            'deliverables' => [
                'Workflow audit and automation opportunity mapping',
                'CI/CD and deployment pipeline setup',
                'Operational alerting and observability improvements',
                'Documentation and handover for internal teams',
            ],
            'timeline' => '2-6 weeks',
            'recommended_technologies' => ['Python', 'AWS', 'Laravel', 'Firebase', 'Docker', 'Redis'],
        ],
    ],

    'projects' => [
        'medical-crm' => [
            'slug' => 'medical-crm',
            'title' => 'Medical CRM',
            'image' => 'images/projects/medical-crm-platform.png',
            'summary' => 'Medical CRM and RCM command center connecting patient, provider, workflow, claim, and KPI operations.',
            'description' => 'A unified medical CRM for patient and provider records, EMR-connected workflows, workload tracking, authorization, eligibility, credentialing, communication, and analytics dashboards covering major healthcare revenue-cycle KPIs.',
            'challenge' => 'Healthcare teams needed one secure platform for patient and provider relationships, fragmented EMR and RCM workflows, claim performance, authorization status, credentialing activity, team workload, and financial outcomes.',
            'solution' => 'We designed a medical CRM command center with role-based patient and provider records, EMR workflow management, authorization and eligibility queues, credentialing alerts, communication history, claim-status reporting, A/R aging, denial analysis, clean claim rate, net collection rate, turnaround time, and workload dashboards.',
            'features' => [
                'Patient, provider, payer, and facility records',
                'EMR-linked documents and role-based workflows',
                'Communication, follow-up, and workload tracking',
                'Workload and turnaround-time tracking',
                'Authorization and eligibility workflows',
                'Provider credentialing alerts',
                'Revenue, claims, denials, aging, and collection dashboards',
            ],
            'results' => [
                'Unified medical relationship and operational visibility',
                'Reduced dependency on disconnected spreadsheets and manual status checks',
                'Clear oversight of patient, provider, claim, and pending team tasks',
                'Leadership-ready analytics for revenue, claims, denials, aging, and collections',
            ],
            'metrics' => [
                'Major RCM KPIs consolidated in one command center',
                'Authorization, eligibility, and credentialing status tracked centrally',
                'Patient, provider, payer, and team activity connected',
            ],
            'industry' => 'Medical CRM & RCM',
            'duration' => '20 weeks',
            'platform' => 'Secure Web Platform',
            'tags' => ['Laravel', 'React', 'PostgreSQL', 'AWS', 'Docker', 'Redis'],
        ],
        'agentic-ai-platform' => [
            'slug' => 'agentic-ai-platform',
            'title' => 'Agentic AI Platform',
            'image' => 'images/projects/agentic-ai-platform.jpg',
            'summary' => 'Autonomous AI agents that understand goals, coordinate tools, execute workflows, and preserve human oversight.',
            'description' => 'An enterprise Agentic AI platform for orchestrating intelligent agents across research, document processing, operations, customer support, analytics, and internal business workflows.',
            'challenge' => 'Teams needed to automate multi-step knowledge work while maintaining security, traceability, approval controls, and reliable integration with existing systems.',
            'solution' => 'We designed a modular agent orchestration layer with task planning, tool calling, retrieval-augmented knowledge, workflow memory, human approval checkpoints, audit logs, model evaluation, and secure API integrations.',
            'features' => [
                'Goal-based autonomous task planning',
                'Multi-agent orchestration and tool calling',
                'Private knowledge retrieval and document analysis',
                'Human approval and escalation checkpoints',
                'Agent activity logs, evaluation, and monitoring',
                'Secure integration with CRM, ERP, and internal APIs',
            ],
            'results' => [
                'Complex workflows converted into traceable agent tasks',
                'Human teams retained control over sensitive actions',
                'Reusable agent capabilities connected across departments',
                'Clear monitoring of decisions, tools, and execution status',
            ],
            'metrics' => [
                'One orchestration layer for multiple AI agents and tools',
                'Human-in-the-loop controls embedded in critical workflows',
                'Audit-ready activity history for every agent execution',
            ],
            'industry' => 'Enterprise AI',
            'duration' => '16 weeks',
            'platform' => 'Web Platform + APIs',
            'tags' => ['Python', 'AI', 'PostgreSQL', 'AWS', 'Docker', 'Redis'],
        ],
        'wellora-ai' => [
            'slug' => 'wellora-ai',
            'title' => 'Wellora AI',
            'image' => 'images/projects/wellora-ai-wellness.jpeg',
            'summary' => 'Responsible AI-powered wellness and nutrition platform with personalized recommendations.',
            'description' => 'Wellora AI combines wellness, nutrition, activity tracking, community engagement, visual food analysis, and personalized AI recommendations in one privacy-focused ecosystem.',
            'challenge' => 'The product needed to deliver meaningful personalization across dietary preferences, activity, wellness goals, allergies, sensitivities, weight objectives, and lifestyle habits while keeping health-related data transparent and user-controlled.',
            'solution' => 'We built the mobile application, backend architecture, data pipelines, custom LLM-based recommendation engine, visual AI meal analysis, health metric integrations, community features, leaderboards, and premium subscriptions. Custom models were trained using 10,000+ wellness and nutrition datasets.',
            'features' => [
                'Personalized meal planning',
                'Smart nutrition and habit recommendations',
                'AI-powered meal recognition and food analysis',
                'Activity, wellness, and health metric integrations',
                'Community engagement and leaderboards',
                'AI wellness assistant and premium subscriptions',
            ],
            'notice' => 'Wellora AI is a wellness and nutrition coaching platform. It is not a medical device and does not provide diagnosis, treatment, disease monitoring, or clinical decision support.',
            'results' => [
                'Personalized meal plans and smart nutrition recommendations',
                'Visual AI for meal recognition and food analysis',
                'Activity, health metric, habit, and wellness tracking',
                'Privacy-first controls with responsible AI positioning',
            ],
            'metrics' => [
                '10,000+ wellness and nutrition datasets used for model development',
                'One ecosystem for nutrition, activity, community, and AI guidance',
                'Custom LLM and visual AI capabilities integrated into the product',
            ],
            'industry' => 'AI Health & Wellness',
            'duration' => '24 weeks',
            'platform' => 'Android + iOS + Cloud',
            'tags' => ['Flutter', 'Python', 'AI', 'Firebase', 'AWS', 'PostgreSQL'],
        ],
        'food-marketplace-platform' => [
            'slug' => 'food-marketplace-platform',
            'title' => 'Food Marketplace Platform',
            'image' => 'images/projects/food-marketplace-platform.png',
            'summary' => 'Restaurant marketplace connecting vendors, customers, orders, menus, and delivery workflows.',
            'description' => 'A scalable food marketplace that helps restaurants list their business, manage dishes, receive real-time orders, coordinate delivery, and build stronger customer relationships.',
            'challenge' => 'Restaurants needed a simple digital workflow for onboarding, menu management, incoming orders, delivery visibility, and customer engagement without operating multiple disconnected tools.',
            'solution' => 'We designed a mobile-first marketplace with restaurant onboarding, menu and dish management, real-time order notifications, order-status tracking, delivery workflows, secure payments, customer discovery, and an administration platform.',
            'features' => [
                'Restaurant onboarding and profile management',
                'Menu, dish, and availability management',
                'Real-time order notifications',
                'Customer order and delivery tracking',
                'Secure payment and marketplace administration',
                'Vendor, customer, delivery, and admin workflows',
            ],
            'results' => [
                'Single workflow for restaurant onboarding and menu operations',
                'Real-time order visibility for restaurants and customers',
                'Structured delivery tracking from acceptance to completion',
                'Scalable foundation for multi-vendor marketplace growth',
            ],
            'metrics' => [
                'Vendor, customer, admin, and delivery workflows connected',
                'Real-time order and delivery status supported',
                'Cross-platform mobile experience with centralized backend',
            ],
            'industry' => 'Food Marketplace',
            'duration' => '18 weeks',
            'platform' => 'Android + iOS + Admin',
            'tags' => ['Flutter', 'Laravel', 'Firebase', 'MySQL', 'Stripe', 'AWS'],
        ],
        'food-app' => [
            'slug' => 'food-app',
            'title' => 'Food App',
            // 'image' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1400&q=80',
            'image' => 'images/food_app.png?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'A hybrid mobile app for ordering food.',
            'description' => 'This project delivered a mobile-first ordering experience with fast checkout, real-time order tracking, and a loyalty flow for repeat customers.',
            'challenge' => 'The client needed a fast ordering flow that could handle peak-time load while keeping onboarding simple for first-time users.',
            'solution' => 'We built a Flutter app with Firebase-backed notifications and Stripe integration, then optimized catalog and checkout for low-latency usage.',
            'results' => [
                'Faster checkout journey with fewer user drop-offs',
                'Real-time order visibility for customers and staff',
                'Scalable architecture ready for expansion',
            ],
            'metrics' => [
                '28% increase in repeat monthly orders',
                '41% faster checkout completion',
                '4.7/5 average app-store rating in first quarter',
            ],
            'industry' => 'Food & Delivery',
            'duration' => '14 weeks',
            'platform' => 'Android + iOS',
            'tags' => ['Flutter', 'Firebase', 'Stripe'],
        ],
        'health-app' => [
            'slug' => 'health-app',
            'title' => 'Health App',
            'image' => 'images/hewie.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Cross-platform mobile app for tracking workouts and health metrics.',
            'description' => 'A complete health tracking product with wearable integration, analytics dashboards, and personalized recommendations powered by an AI model.',
            'challenge' => 'Data consistency between multiple health providers and wearables created syncing and reporting complexity.',
            'solution' => 'We implemented a normalized health-data layer with integrations for Samsung Health and HealthKit, then added analytics and recommendation modules.',
            'results' => [
                'Unified tracking across Android and iOS',
                'Improved user retention through personalized insights',
                'Reliable health data sync at scale',
            ],
            'metrics' => [
                '31% lift in weekly active users',
                '22% increase in workout completion rate',
                'Sync reliability above 99.2%',
            ],
            'industry' => 'Healthcare',
            'duration' => '18 weeks',
            'platform' => 'Android + iOS',
            'tags' => ['Android', 'iOS', 'Samsung Health', 'Health Kit', 'Firebase', 'AI Model'],
        ],
        'usb-camera' => [
            'slug' => 'usb-camera',
            'title' => 'USB Camera',
            'image' => 'images/SIMS.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1581092921461-eab10380a4c1?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'For medical purpose. To capture images from an external camera and store as PDF.',
            'description' => 'A medical utility app for USB camera capture, image management, and secure PDF generation for patient records.',
            'challenge' => 'Medical teams required a reliable workflow to capture images through external hardware and export structured documents quickly.',
            'solution' => 'We developed Android USB camera support with a guided capture flow, metadata tagging, and on-device PDF generation.',
            'results' => [
                'Reduced manual steps in clinical documentation',
                'Consistent PDF output with clear image quality',
                'Stable external camera support in production environments',
            ],
            'metrics' => [
                '55% reduction in report creation time',
                'Near-zero image upload failures post launch',
            ],
            'industry' => 'Healthcare',
            'duration' => '10 weeks',
            'platform' => 'Android',
            'tags' => ['Android', 'Firebase', 'External Camera', 'PDF Conversion'],
        ],
        'aimshala' => [
            'slug' => 'aimshala',
            'title' => 'Aimshala',
            'image' => 'images/aimshala.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Empowering Career Paths with AI-Driven Guidance.',
            'description' => 'An education and career guidance platform combining assessments, mentorship workflows, and AI-powered recommendation pipelines.',
            'challenge' => 'Students required practical, personalized guidance while administrators needed tools to manage large user cohorts.',
            'solution' => 'We built a Laravel-powered platform with role-based dashboards, recommendation logic, and Python-based AI components.',
            'results' => [
                'Improved student engagement through personalized paths',
                'Efficient admin workflows for advisors and mentors',
                'Strong foundation for ongoing AI feature expansion',
            ],
            'metrics' => [
                '48% increase in mentorship session bookings',
                '36% faster counselor workflow completion',
            ],
            'industry' => 'Education',
            'duration' => '16 weeks',
            'platform' => 'Web Platform',
            'tags' => ['Laravel', 'PHP', 'HTML/CSS', 'MySQL', 'Python', 'AI'],
        ],
        'admin-dashboard' => [
            'slug' => 'admin-dashboard',
            'title' => 'Admin Dashboard',
            'image' => 'images/Fitzme_ok.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Business intelligence platform with real-time data visualization.',
            'description' => 'A centralized dashboard experience enabling teams to monitor metrics, review trends, and take faster operational decisions.',
            'challenge' => 'Decision-makers lacked a unified reporting interface and had to combine fragmented data manually.',
            'solution' => 'We delivered a Laravel-based dashboard with reusable widgets, role-level access, and optimized reporting endpoints.',
            'results' => [
                'Single source of truth for operational metrics',
                'Faster reporting and decision cycles',
                'Extensible architecture for future modules',
            ],
            'metrics' => [
                '42% reduction in manual reporting effort',
                'Real-time analytics for 12+ departments',
            ],
            'industry' => 'Enterprise Tools',
            'duration' => '12 weeks',
            'platform' => 'Web Dashboard',
            'tags' => ['Laravel', 'PHP', 'HTML/CSS', 'MySQL', 'Redis'],
        ],
        'commerce-suite' => [
            'slug' => 'commerce-suite',
            'title' => 'Commerce Suite',
            'image' => 'images/ecommerce_website.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Omnichannel ecommerce platform with catalog, checkout, and order automation.',
            'description' => 'A scalable ecommerce system with inventory sync, promotional engine, and optimized checkout funnel for repeat purchases.',
            'challenge' => 'Multiple catalogs and seasonal campaigns created operational overhead and inconsistent user journeys.',
            'solution' => 'We designed a modular storefront + admin suite with centralized product management and analytics-driven campaign controls.',
            'results' => [
                'Unified operations for multi-category catalogs',
                'Improved conversion through optimized checkout flow',
                'Lower support load with better order visibility',
            ],
            'metrics' => [
                '19% improvement in checkout conversion',
                '27% increase in average order value',
            ],
            'industry' => 'E-commerce',
            'duration' => '20 weeks',
            'platform' => 'Web + Admin',
            'tags' => ['Next.js', 'Laravel', 'MySQL', 'Stripe', 'AWS'],
        ],
        'eduflow-campus' => [
            'slug' => 'eduflow-campus',
            'title' => 'EduFlow Campus',
            'image' => 'images/education.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Academic operations platform for attendance, assignments, and guardian communication.',
            'description' => 'A unified student lifecycle platform helping institutes digitize daily operations and communication.',
            'challenge' => 'Institutes were running attendance, assignment tracking, and parent communication in disconnected tools.',
            'solution' => 'We introduced a role-based web portal and mobile app for students, teachers, and parents with centralized notifications.',
            'results' => [
                'Better transparency between faculty and guardians',
                'Reduced administrative work through automation',
                'Improved academic workflow consistency',
            ],
            'metrics' => [
                '37% faster assignment review cycle',
                '62% parent app adoption in first semester',
            ],
            'industry' => 'Education',
            'duration' => '15 weeks',
            'platform' => 'Web + Mobile',
            'tags' => ['React Native', 'Laravel', 'Firebase', 'MySQL'],
        ],
        'fleet-track-pro' => [
            'slug' => 'fleet-track-pro',
            'title' => 'Fleet Track Pro',
            'image' => 'images/logistic.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1563770660941-10a63607692e?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Logistics control panel and driver app for live fleet tracking and dispatch automation.',
            'description' => 'A logistics platform connecting dispatch managers and drivers with route-level visibility, alerts, and trip analytics.',
            'challenge' => 'The client needed to reduce delays caused by manual assignment and missing delivery visibility.',
            'solution' => 'We built a web command center and mobile companion app with geolocation updates, route assignment, and delay notifications.',
            'results' => [
                'Higher dispatch accuracy across regional routes',
                'Real-time visibility for operations teams',
                'Reduced response time for route changes',
            ],
            'metrics' => [
                '23% improvement in on-time deliveries',
                '34% reduction in manual dispatch calls',
            ],
            'industry' => 'Logistics',
            'duration' => '17 weeks',
            'platform' => 'Web + Mobile',
            'tags' => ['React', 'Laravel', 'PostgreSQL', 'AWS', 'Redis'],
        ],
        'travelmate-booking' => [
            'slug' => 'travelmate-booking',
            'title' => 'TravelMate Booking',
            'image' => 'images/travel.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Travel booking portal with itinerary management, payment, and partner dashboards.',
            'description' => 'A travel platform for itinerary planning, booking workflows, and operator-side schedule management.',
            'challenge' => 'The existing platform had low conversion due to poor mobile flow and delayed booking confirmations.',
            'solution' => 'We redesigned the booking funnel, integrated payment automation, and added role-based dashboards for operators.',
            'results' => [
                'Smoother booking flow on mobile and desktop',
                'Improved operator handling for booking requests',
                'Faster confirmation cycle for customers',
            ],
            'metrics' => [
                '26% increase in booking completion',
                '44% decrease in manual confirmation time',
            ],
            'industry' => 'Travel',
            'duration' => '13 weeks',
            'platform' => 'Web Platform',
            'tags' => ['Next.js', 'Laravel', 'MySQL', 'Stripe', 'Redis'],
        ],
        'finpulse-analytics' => [
            'slug' => 'finpulse-analytics',
            'title' => 'FinPulse Analytics',
            'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Finance analytics suite with role-based BI dashboards and automated reporting.',
            'description' => 'A data-intensive analytics system for finance teams with secure access, dashboard customization, and scheduled reports.',
            'challenge' => 'Stakeholders relied on disconnected spreadsheets and lacked a trustworthy real-time reporting layer.',
            'solution' => 'We built a centralized dashboard suite with secure APIs, charting modules, and scheduled report delivery.',
            'results' => [
                'Consolidated reporting for leadership teams',
                'Improved data confidence through unified sources',
                'Faster insight generation for weekly reviews',
            ],
            'metrics' => [
                '52% reduction in weekly report preparation time',
                '93% dashboard adoption across finance teams',
            ],
            'industry' => 'Fintech',
            'duration' => '19 weeks',
            'platform' => 'Web Dashboard',
            'tags' => ['React', 'Laravel', 'PostgreSQL', 'AWS', 'Docker'],
        ],
        'motion-design-suite' => [
            'slug' => 'motion-design-suite',
            'title' => 'Motion Design Suite',
            'image' => 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Interactive product website with design-system driven UI and cinematic animations.',
            'description' => 'A conversion-focused web experience built to present product value through polished motion and clear UI hierarchy.',
            'challenge' => 'The client needed a premium visual experience while keeping page speed and responsiveness stable.',
            'solution' => 'We built the frontend with TypeScript and Framer Motion, created reusable Figma components, and optimized rendering for smooth transitions.',
            'results' => [
                'Stronger user engagement through meaningful animations',
                'Consistent brand visuals with reusable design components',
                'Improved conversion flow clarity across landing pages',
            ],
            'metrics' => [
                '38% increase in average time on page',
                '21% improvement in CTA click-through rate',
            ],
            'industry' => 'SaaS Platforms',
            'duration' => '11 weeks',
            'platform' => 'Web Platform',
            'tags' => ['Figma', 'Framer Motion', 'TypeScript', 'React', 'AWS'],
        ],
        'native-cart-plus' => [
            'slug' => 'native-cart-plus',
            'title' => 'Native Cart Plus',
            'image' => 'images/ecommerce.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1551817958-20204e8c71c8?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Cross-platform shopping app with realtime inventory and cart sync.',
            'description' => 'A mobile commerce app focused on fast onboarding, personalized catalog browsing, and reliable cart state across sessions.',
            'challenge' => 'The business needed one codebase for iOS and Android with fast release cycles and stable payment journeys.',
            'solution' => 'We implemented the app in React Native with TypeScript, Firebase-backed sync events, and API orchestration for inventory and checkout.',
            'results' => [
                'Single release pipeline for Android and iOS',
                'Stable inventory sync during high traffic periods',
                'Improved checkout experience for returning users',
            ],
            'metrics' => [
                '29% reduction in cart abandonment',
                '3.5x faster feature release cycle',
            ],
            'industry' => 'E-commerce',
            'duration' => '14 weeks',
            'platform' => 'Android + iOS',
            'tags' => ['React Native', 'TypeScript', 'Firebase', 'MySQL', 'AWS'],
        ],
        'smart-crm-hub' => [
            'slug' => 'smart-crm-hub',
            'title' => 'Smart CRM Hub',
            'image' => 'images/crm.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Cloud CRM platform for lead tracking, sales pipelines, and automated follow-ups.',
            'description' => 'A CRM solution designed for sales teams to manage lead flow, automate tasks, and improve conversion visibility.',
            'challenge' => 'Sales teams were using spreadsheets and missed follow-up opportunities due to fragmented workflows.',
            'solution' => 'We built a Laravel + React CRM with activity timelines, automation triggers, and role-based dashboards.',
            'results' => [
                'Centralized lead lifecycle management',
                'Reduced missed follow-ups with automated reminders',
                'Improved visibility into conversion stages',
            ],
            'metrics' => [
                '33% increase in qualified lead conversion',
                '46% faster response time on incoming leads',
            ],
            'industry' => 'SaaS Platforms',
            'duration' => '15 weeks',
            'platform' => 'Web Platform',
            'tags' => ['Laravel', 'React', 'MySQL', 'Redis', 'TypeScript'],
        ],
        'iot-monitor-grid' => [
            'slug' => 'iot-monitor-grid',
            'title' => 'IoT Monitor Grid',
            'image' => 'https://images.unsplash.com/photo-1580894908361-967195033215?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Device monitoring dashboard with real-time telemetry, alerts, and maintenance workflows.',
            'description' => 'An industrial monitoring application for tracking device health, anomaly alerts, and preventative maintenance schedules.',
            'challenge' => 'Operations teams lacked centralized monitoring and could not detect failures early.',
            'solution' => 'We delivered an event-driven dashboard with PostgreSQL analytics storage and alert automation.',
            'results' => [
                'Improved operational visibility across device fleets',
                'Faster issue detection and response cycles',
                'Reliable incident history for maintenance planning',
            ],
            'metrics' => [
                '58% faster anomaly detection',
                '27% reduction in unplanned downtime',
            ],
            'industry' => 'Industrial Tech',
            'duration' => '18 weeks',
            'platform' => 'Web Dashboard',
            'tags' => ['Python', 'PostgreSQL', 'AWS', 'Docker', 'React'],
        ],
        'community-social-app' => [
            'slug' => 'community-social-app',
            'title' => 'Community Social App',
            'image' => 'images/MyTalent.png?auto=format&fit=crop&w=1400&q=80',
            // 'image' => 'https://images.unsplash.com/photo-1526498460520-4c246339dccb?auto=format&fit=crop&w=1400&q=80',
            'summary' => 'Social community app with groups, feed, events, and live engagement modules.',
            'description' => 'A community-first application allowing users to create groups, publish updates, and manage event participation.',
            'challenge' => 'The organization needed stronger digital engagement for distributed communities.',
            'solution' => 'We built a Flutter app with Firebase realtime features and admin moderation controls.',
            'results' => [
                'Higher community interaction and retention',
                'Improved moderation workflows',
                'Faster event communication cycles',
            ],
            'metrics' => [
                '2.2x increase in weekly active users',
                '64% participation rate in app events',
            ],
            'industry' => 'Community Platforms',
            'duration' => '13 weeks',
            'platform' => 'Android + iOS',
            'tags' => ['Flutter', 'Firebase', 'TypeScript', 'AWS'],
        ],
    ],

    'process' => [
        [
            'slug' => 'discovery',
            'number' => '01',
            'icon' => '💡',
            'icon_class' => 'icon-blue',
            'title' => 'Discovery',
            'summary' => 'We define scope, user goals, constraints, and technical priorities before implementation starts.',
            'activities' => [
                'Business and stakeholder workshops',
                'User persona and requirement mapping',
                'Risk identification and technical planning',
            ],
            'deliverables' => [
                'Project scope document',
                'Feature priority list',
                'Execution roadmap with milestones',
            ],
        ],
        [
            'slug' => 'design',
            'number' => '02',
            'icon' => '🎨',
            'icon_class' => 'icon-pink',
            'title' => 'Design',
            'summary' => 'We transform requirements into wireframes, prototypes, and system-ready UI components.',
            'activities' => [
                'Information architecture',
                'Wireframe and interaction planning',
                'Visual design system creation',
            ],
            'deliverables' => [
                'User flow map',
                'Interactive product prototype',
                'Design system and component standards',
            ],
        ],
        [
            'slug' => 'development',
            'number' => '03',
            'icon' => '</>',
            'icon_class' => 'icon-orange',
            'title' => 'Development',
            'summary' => 'Our engineers build secure, scalable systems using clean architecture and production practices.',
            'activities' => [
                'Frontend and backend implementation',
                'API development and integration',
                'Code review and quality automation',
            ],
            'deliverables' => [
                'Production-ready codebase',
                'Integrated APIs and data models',
                'Staging build for UAT',
            ],
        ],
        [
            'slug' => 'launch-and-growth',
            'number' => '04',
            'icon' => '🚀',
            'icon_class' => 'icon-green',
            'title' => 'Launch & Growth',
            'summary' => 'We release, monitor, and optimize your product with continuous improvement cycles.',
            'activities' => [
                'Deployment and release validation',
                'Monitoring and incident readiness',
                'Feedback-based feature iteration',
            ],
            'deliverables' => [
                'Go-live checklist completion',
                'Performance and reliability dashboard',
                'Post-launch optimization plan',
            ],
        ],
    ],

    'technologies' => [
        [
            'name' => 'Laravel',
            'category' => 'Backend',
            'summary' => 'Robust PHP framework for secure APIs, enterprise workflows, and scalable web platforms.',
            'use_cases' => 'Business systems, admin dashboards, CRMs, and service platforms.',
            'similar_stack' => ['Node.js', 'Django'],
        ],
        [
            'name' => 'React',
            'category' => 'Frontend',
            'summary' => 'Component-driven frontend framework for fast, dynamic, and interactive user interfaces.',
            'use_cases' => 'SaaS dashboards, data-heavy portals, modern web apps.',
            'similar_stack' => ['Vue.js', 'Svelte'],
        ],
        [
            'name' => 'Next.js',
            'category' => 'Frontend',
            'summary' => 'React framework optimized for SEO, server rendering, and performance-first websites.',
            'use_cases' => 'Marketing websites, content platforms, hybrid web applications.',
            'similar_stack' => ['Nuxt', 'Remix'],
        ],
        [
            'name' => 'Flutter',
            'category' => 'Mobile',
            'summary' => 'Cross-platform toolkit for high-quality iOS and Android apps from one codebase.',
            'use_cases' => 'Consumer apps, on-demand apps, startup MVPs with fast release cycles.',
            'similar_stack' => ['React Native', 'Kotlin Multiplatform'],
        ],
        [
            'name' => 'React Native',
            'category' => 'Mobile',
            'summary' => 'Cross-platform mobile framework using JavaScript ecosystem and reusable components.',
            'use_cases' => 'Multi-platform mobile products with shared business logic.',
            'similar_stack' => ['Flutter', 'Ionic'],
        ],
        [
            'name' => 'Firebase',
            'category' => 'Cloud',
            'summary' => 'Backend-as-a-service for authentication, real-time data, analytics, and notifications.',
            'use_cases' => 'Rapid MVP delivery, mobile backends, event-based app features.',
            'similar_stack' => ['Supabase', 'AWS Amplify'],
        ],
        [
            'name' => 'MySQL',
            'category' => 'Database',
            'summary' => 'Reliable relational database for transactional data and structured reporting.',
            'use_cases' => 'ERP modules, customer data platforms, operational reporting.',
            'similar_stack' => ['PostgreSQL', 'MariaDB'],
        ],
        [
            'name' => 'PostgreSQL',
            'category' => 'Database',
            'summary' => 'Advanced relational database with strong indexing and analytics-friendly querying.',
            'use_cases' => 'Complex data platforms, analytics-heavy SaaS products, enterprise workloads.',
            'similar_stack' => ['MySQL', 'CockroachDB'],
        ],
        [
            'name' => 'Python',
            'category' => 'AI & Automation',
            'summary' => 'Flexible language for automation, analytics pipelines, and AI feature integration.',
            'use_cases' => 'Recommendation engines, workflow automation, data processing.',
            'similar_stack' => ['R', 'Node.js'],
        ],
        [
            'name' => 'AWS',
            'category' => 'Cloud',
            'summary' => 'Cloud infrastructure stack for secure deployments, scaling, and high availability.',
            'use_cases' => 'Production hosting, autoscaling APIs, distributed system infrastructure.',
            'similar_stack' => ['Azure', 'Google Cloud'],
        ],
        [
            'name' => 'Docker',
            'category' => 'DevOps',
            'summary' => 'Containerization platform for consistent environments and reliable deployment pipelines.',
            'use_cases' => 'Microservices, CI/CD reproducibility, multi-environment parity.',
            'similar_stack' => ['Podman', 'Kubernetes'],
        ],
        [
            'name' => 'Redis',
            'category' => 'Performance',
            'summary' => 'In-memory data store for caching, sessions, and real-time workloads.',
            'use_cases' => 'API acceleration, queue management, live counters and dashboards.',
            'similar_stack' => ['Memcached', 'KeyDB'],
        ],
        [
            'name' => 'TypeScript',
            'category' => 'Language',
            'summary' => 'Typed JavaScript for safer, scalable frontend and full-stack codebases.',
            'use_cases' => 'Large-scale apps, team collaboration, maintainable long-term code.',
            'similar_stack' => ['Flow', 'JavaScript'],
        ],
        [
            'name' => 'Figma',
            'category' => 'Design',
            'summary' => 'Collaborative UI/UX design platform for prototypes, systems, and handoff workflows.',
            'use_cases' => 'Design systems, prototyping, team design collaboration.',
            'similar_stack' => ['Adobe XD', 'Sketch'],
        ],
        [
            'name' => 'Framer Motion',
            'category' => 'Frontend Motion',
            'summary' => 'Animation library for expressive user interactions and smooth component transitions.',
            'use_cases' => 'Interactive landing pages, micro-interactions, polished product experiences.',
            'similar_stack' => ['GSAP', 'Lottie'],
        ],
    ],

    'testimonials' => [
        [
            'name' => 'Liban Hassan',
            'role' => 'Founder & Chief Executive Officer',
            'company' => 'efiri App',
            'country' => 'Somalia',
            'image' => 'images/reviews/liban-hassan.webp',
            'rating' => 5,
            'review' => 'Working with this team was a very smooth and professional experience. They understood our application requirements clearly and delivered the project with proper communication, clean development, and reliable support. I am happy with the final result and would recommend them for mobile app development.',
            'project' => 'Mobile App Development',
        ],
        [
            'name' => 'Émilie Laurent',
            'role' => 'Business Development Manager',
            'company' => '',
            'country' => 'France',
            'image' => 'images/reviews/emilie-laurent.png',
            'rating' => 5,
            'review' => 'The team delivered a modern and user-friendly digital solution for our business. Their technical understanding, attention to detail, and professional communication made the entire development process easy and transparent.',
            'project' => 'Digital Solution Delivery',
        ],
        [
            'name' => 'Aarav Mehta',
            'role' => 'Founder',
            'company' => 'Digital Commerce Brand',
            'country' => 'India',
            'image' => '',
            'rating' => 5,
            'review' => 'They helped us build a complete mobile app with a clean interface and smooth performance. The team was responsive, professional, and focused on delivering quality work within the agreed timeline.',
            'project' => 'Mobile Commerce App',
        ],
        [
            'name' => 'James Walker',
            'role' => 'Managing Director',
            'company' => '',
            'country' => 'United Kingdom',
            'image' => 'images/reviews/james-walker.png',
            'rating' => 5,
            'review' => 'We were impressed by their ability to understand business goals and convert them into a functional application. Their development process was well-organized, and the final product met our expectations.',
            'project' => 'Business Application',
        ],
        [
            'name' => 'Olivia Bennett',
            'role' => 'Operations Head',
            'company' => '',
            'country' => 'Canada',
            'image' => 'images/reviews/olivia-bennett.png',
            'rating' => 5,
            'review' => 'The project was handled with professionalism from start to finish. They provided clear updates, solved technical challenges quickly, and delivered a scalable solution suitable for our business needs.',
            'project' => 'Scalable Business Platform',
        ],
        [
            'name' => 'Ahmed Al Mansoori',
            'role' => 'Founder & CEO',
            'company' => '',
            'country' => 'United Arab Emirates',
            'image' => 'images/reviews/ahmed-al-mansoori.png',
            'rating' => 5,
            'review' => 'They developed a reliable and professional mobile application for our business. Their team understood our market needs and provided a solution that was easy to use, secure, and well-structured.',
            'project' => 'Secure Mobile Application',
        ],
        [
            'name' => 'Sophia Carter',
            'role' => 'Product Manager',
            'company' => '',
            'country' => 'United States',
            'image' => 'images/reviews/sophia-carter.png',
            'rating' => 5,
            'review' => 'Their team showed strong technical skills and excellent communication throughout the project. The app was delivered with a clean design, smooth functionality, and proper attention to user experience.',
            'project' => 'Product Experience App',
        ],
    ],

    'packages' => [
        [
            'id' => 'starter-web',
            'name' => 'Starter Web Package',
            'technology_focus' => ['Laravel', 'React', 'Next.js'],
            'best_for' => 'Startups and local businesses',
            'price' => '$899',
            'timeline' => '2-3 weeks',
            'includes' => [
                'Up to 6 responsive pages',
                'Basic SEO setup',
                'Contact form + WhatsApp integration',
                'Deployment support',
            ],
            'deliverables' => [
                'UI mockups for key pages',
                'Mobile-first page implementation',
                'Basic analytics + tracking setup',
                'Launch checklist and documentation',
            ],
            'our_value' => 'Dedicated support and custom design with direct founder communication.',
            'other_platforms' => '$1,100 - $1,600',
        ],
        [
            'id' => 'growth-app',
            'name' => 'Growth App Package',
            'technology_focus' => ['Flutter', 'React Native', 'Firebase', 'Laravel'],
            'best_for' => 'Growing products with active users',
            'price' => '$2,900',
            'timeline' => '5-8 weeks',
            'includes' => [
                'Web app or mobile app MVP',
                'Authentication and dashboard',
                'Admin panel and analytics basics',
                'QA and launch assistance',
            ],
            'deliverables' => [
                'Requirements workshop + product blueprint',
                'Core feature implementation',
                'Admin control panel',
                'Testing pass and deployment support',
            ],
            'our_value' => 'Product-focused architecture with scalable codebase and milestone-based delivery.',
            'other_platforms' => '$3,500 - $6,000',
        ],
        [
            'id' => 'scale-suite',
            'name' => 'Scale Suite Package',
            'technology_focus' => ['AWS', 'Docker', 'Redis', 'Laravel', 'PostgreSQL'],
            'best_for' => 'Enterprises or high-growth teams',
            'price' => '$5,900',
            'timeline' => '10-14 weeks',
            'includes' => [
                'Multi-role platform architecture',
                'Automation + CI/CD setup',
                'Performance tuning + security hardening',
                'Post-launch optimization cycle',
            ],
            'deliverables' => [
                'Architecture planning with growth roadmap',
                'Staging + production environments',
                'Performance and security audit',
                'Operational handover with team training',
            ],
            'our_value' => 'Senior team execution, strong documentation, and long-term product maintainability.',
            'other_platforms' => '$8,000 - $14,000',
        ],
        [
            'id' => 'custom',
            'name' => 'Custom Build Package',
            'technology_focus' => ['Any Stack'],
            'best_for' => 'Custom requirements, hybrid products, or phased development',
            'price' => 'Custom Quote',
            'timeline' => 'Depends on scope',
            'includes' => [
                'Requirement breakdown call',
                'Technology recommendation by use-case',
                'Phased roadmap with milestones',
                'Budget-friendly sprint planning',
            ],
            'deliverables' => [
                'Technical proposal document',
                'Effort estimate and timeline',
                'Delivery model options',
                'Execution kickoff plan',
            ],
            'our_value' => 'Built around your exact requirement with flexible budget and timeline planning.',
            'other_platforms' => 'Often unclear / variable',
        ],
    ],

    'industries' => [
        'Healthcare',
        'Education',
        'Food & Delivery',
        'SaaS Platforms',
        'E-commerce',
        'Internal Enterprise Tools',
    ],
];
